feat: update firefox install script

diff --git a/install/firefox b/install/firefox
--- a/install/firefox
+++ b/install/firefox
@@ -1,52 +1,68 @@
 #!/bin/sh
 set -e
 
-self="$(realpath $(dirname $0))"
+self="${0%/*}"; [ "$self" = "$0" ] && self="."
 . "$self/../shell/.functions"
 
-platform="$(detect_platform)"
+platform="$(get_platform)"
 case "$platform" in
   linux-amd64) platform="linux-x86_64";;
   *) die "unsupported platform: $platform";;
 esac
 
-show_help() {
-  echo "Usage: firefox [options]"
+version='142.0.1'
+language='en-US'
+
+usage() {
+  echo "Usage: "$0" [options]"
   echo ""
   echo "Options:"
-  echo "  -version   Firefox version to install (default 142.0.1)"
-  echo "  -lang      Language to install (default en-US)"
-  echo "  --help     Show this help message"
+  echo "  -h, --help   Show this help message"
+  echo "  -version     Firefox version (default '$version')"
+  echo "  -lang        Firefox language (default '$language')"
 }
 
 while [ $# -gt 0 ]; do
   case "$1" in
-    -version) version="$(get_option $@)"; shift 2;;
-    -lang) language="$(get_option $@)"; shift 2;;
-    --help) show_help; exit 0;;
-    -*) die help "Unknown option '$1'";;
-    *) die help "No arguments allowed";;
+    -h|--help) usage; exit 0;;
+    -version) 
+      version="$(get_opt "$@")"
+      [ -z "$version" ] && die "Version cannot be empty"
+      shift 2
+      ;;
+    -lang) 
+      language="$(get_opt "$@")"
+      [ -z "$language" ] && die "Language cannot be empty"
+      shift 2
+      ;;
+    -*) die -h "Unknown option '$1'";;
+    *) die -h "No arguments allowed";;
   esac
 done
 
-version="${version:-"142.0.1"}"
-language="${language:-"en-US"}"
-echo "Install Firefox $version in $language"
-
 url="https://download-installer.cdn.mozilla.net/pub/firefox/releases/"\
 "$version/$platform/$language/firefox-$version.tar.xz"
-
 dest="$HOME/opt"
-mkdir -p $dest
-[ -d "$dest/firefox" ] && die "$dest/firefox exists, skip download"
 
-cd "$HOME/opt"
-"$self/download" -axel "$url" "$outfile"
-outfile="${url##*/}"
-echo $outfile
-# [ -f $outfile ] && rm "$outfile"
-#
-# tar xf "$outfile"
-# rm "$outfile"
+[ -d "$dest/firefox" ] && {
+  log warning "$dest/firefox exists, skip download"
+  log info "To reinstall, remove $dest/firefox first"
+  exit 0
+}
 
+[ -d "$dest" ] || {
+  need_cmd mkdir
+  mkdir -p "$dest"
+}
+
+outfile="$dest/${url##*/}"
+"$self/download" -x "$url" -o "$outfile"
+
+log info "Extracting Firefox tarball..."
+need_cmd tar
+need_cmd rm
+tar xf "$outfile" -C "$dest" || die "Failed to extract Firefox tarball"
+rm "$outfile"
+
+log success "Firefox $version installed to $dest/firefox"
 
